name: StaffCommandLog
main: io.github.randomkiddo.scl.Main
version: 1.3.7
author: firsttry
commands:
  slog:
    description: Gets the staff command log for a specific player
    usage: /slog player amount(<16)
    permission: scl.op
    permission-message: You don't have permission to do this